export const dummyJunctions = [
  {
    id: 'J-001',
    name: 'SVNIT Junction',
    slug: 'svnit-junction',
    area: 'Ichchhanath / Dumas Rd',
    lat: 21.167790,
    lon: 72.785022,
    latitude: 21.167790,
    longitude: 72.785022,
    status: 'normal',
    num_lanes: 4,
    has_brts: true,
    is_major: true,
    junction_type: 'transit',
    description: 'Key academic and commercial junction along the Dumas corridor with high peak-hour student and commuter transit.',
    connecting_roads: ['Dumas Road', 'Gaurav Path', 'SVNIT Campus Road'],
    google_maps_url: 'https://www.google.com/maps?q=21.167790,72.785022'
  },
  {
    id: 'J-002',
    name: 'Majura Gate BRTS Hub',
    slug: 'majura-gate',
    area: 'Ring Road / Kailash Nagar',
    lat: 21.182450,
    lon: 72.823200,
    latitude: 21.182450,
    longitude: 72.823200,
    status: 'critical',
    num_lanes: 6,
    has_brts: true,
    is_major: true,
    junction_type: 'transit',
    description: 'High-density multi-leg intersection on Ring Road with active BRTS priority corridor and elevated flyover approaches.',
    connecting_roads: ['Ring Road', 'Civil Hospital Road', 'Udhna Main Road'],
    google_maps_url: 'https://www.google.com/maps?q=21.182450,72.823200'
  },
  {
    id: 'J-003',
    name: 'Ghod Dod Road Junction',
    slug: 'ghod-dod-road',
    area: 'Ghod Dod Commercial District',
    lat: 21.175400,
    lon: 72.805200,
    latitude: 21.175400,
    longitude: 72.805200,
    status: 'moderate',
    num_lanes: 4,
    has_brts: false,
    is_major: false,
    junction_type: 'commercial',
    description: 'Premier shopping and retail boulevard junction with substantial commercial and mixed vehicle movement.',
    connecting_roads: ['Ghod Dod Road', 'Subhash Chandra Bose Marg', 'City Light Approach'],
    google_maps_url: 'https://www.google.com/maps?q=21.175400,72.805200'
  },
  {
    id: 'J-004',
    name: 'Sahara Darwaja Junction',
    slug: 'sahara-darwaja',
    area: 'Surat Railway Station Hub',
    lat: 21.196600,
    lon: 72.846500,
    latitude: 21.196600,
    longitude: 72.846500,
    status: 'critical',
    num_lanes: 6,
    has_brts: true,
    is_major: true,
    junction_type: 'transit',
    description: 'Major arterial node connecting the central railway terminus, intercity bus station, and Ring Road wholesale textile market.',
    connecting_roads: ['Station Road', 'Ring Road', 'Varachha Main Road'],
    google_maps_url: 'https://www.google.com/maps?q=21.196600,72.846500'
  },
  {
    id: 'J-005',
    name: 'Udhna Darwaja',
    slug: 'udhna-darwaja',
    area: 'Udhna Main Road / Ring Road',
    lat: 21.179400,
    lon: 72.836200,
    latitude: 21.179400,
    longitude: 72.836200,
    status: 'moderate',
    num_lanes: 6,
    has_brts: true,
    is_major: true,
    junction_type: 'industrial',
    description: 'Arterial hub at Ring Road and Udhna Main Road facilitating heavy commuter and BRTS transit.',
    connecting_roads: ['Ring Road', 'Udhna Main Road', 'Khatodara Link Road'],
    google_maps_url: 'https://www.google.com/maps?q=21.179400,72.836200'
  },
  {
    id: 'J-006',
    name: 'Hirabaug Circle',
    slug: 'hirabaug-circle',
    area: 'Varachha Diamond Corridor',
    lat: 21.216200,
    lon: 72.863500,
    latitude: 21.216200,
    longitude: 72.863500,
    status: 'critical',
    num_lanes: 6,
    has_brts: true,
    is_major: true,
    junction_type: 'commercial',
    description: 'Heart of the global diamond trading hub under Varachha Flyover with high-volume two-wheeler and BRTS flow.',
    connecting_roads: ['Varachha Main Road', 'AK Road', 'Mini Bazaar Road'],
    google_maps_url: 'https://www.google.com/maps?q=21.216200,72.863500'
  },
  {
    id: 'J-007',
    name: 'Adajan Patiya Junction',
    slug: 'adajan-patiya',
    area: 'Adajan Residential Belt',
    lat: 21.198200,
    lon: 72.795200,
    latitude: 21.198200,
    longitude: 72.795200,
    status: 'normal',
    num_lanes: 4,
    has_brts: true,
    is_major: true,
    junction_type: 'residential',
    description: 'Busy transit junction serving high-density residential towers west of the Tapi River with dedicated BRTS stops.',
    connecting_roads: ['LP Savani Road', 'Adajan Hazira Road', 'Rander Road'],
    google_maps_url: 'https://www.google.com/maps?q=21.198200,72.795200'
  },
  {
    id: 'J-008',
    name: 'Athwa Gate / Chowk Bazaar',
    slug: 'athwa-gate',
    area: 'Central Surat Old City',
    lat: 21.188400,
    lon: 72.815400,
    latitude: 21.188400,
    longitude: 72.815400,
    status: 'moderate',
    num_lanes: 4,
    has_brts: false,
    is_major: false,
    junction_type: 'historic',
    description: 'Heritage Old City intersection near Surat Castle and historic Tapi waterfront markets.',
    connecting_roads: ['Nehru Bridge Road', 'Chowk Bazaar Road', 'Raj Bhavan Marg'],
    google_maps_url: 'https://www.google.com/maps?q=21.188400,72.815400'
  },
  {
    id: 'J-009',
    name: 'Delhi Gate Circle',
    slug: 'delhi-gate',
    area: 'Central North Corridor',
    lat: 21.199400,
    lon: 72.833200,
    latitude: 21.199400,
    longitude: 72.833200,
    status: 'critical',
    num_lanes: 6,
    has_brts: true,
    is_major: true,
    junction_type: 'commercial',
    description: 'High-volume crossroads connecting Ring Road commercial markets, Mahidharpura diamond market, and northern transit.',
    connecting_roads: ['Ring Road', 'Sumul Dairy Road', 'Station Link Road'],
    google_maps_url: 'https://www.google.com/maps?q=21.199400,72.833200'
  },
  {
    id: 'J-010',
    name: 'VNSGU University Road',
    slug: 'vnsgu-university-road',
    area: 'Piplod / University Campus',
    lat: 21.153400,
    lon: 72.775400,
    latitude: 21.153400,
    longitude: 72.775400,
    status: 'normal',
    num_lanes: 4,
    has_brts: false,
    is_major: false,
    junction_type: 'residential',
    description: 'Educational corridor intersection providing access to South Gujarat University campus and south-west residential suburbs.',
    connecting_roads: ['University Road', 'Gaurav Path', 'Piplod Canal Road'],
    google_maps_url: 'https://www.google.com/maps?q=21.153400,72.775400'
  },
  {
    id: 'J-011',
    name: 'Katargam Darwaja',
    slug: 'katargam-darwaja',
    area: 'Katargam Industrial Hub',
    lat: 21.215400,
    lon: 72.832400,
    latitude: 21.215400,
    longitude: 72.832400,
    status: 'moderate',
    num_lanes: 4,
    has_brts: true,
    is_major: false,
    junction_type: 'industrial',
    description: 'Textile machinery, diamond cutting workshops, and northern residential link intersection.',
    connecting_roads: ['Katargam Main Road', 'Gotalawadi Road', 'Singanpore Link'],
    google_maps_url: 'https://www.google.com/maps?q=21.215400,72.832400'
  },
  {
    id: 'J-012',
    name: 'Vesu VIP Road Junction',
    slug: 'vesu-vip-road',
    area: 'Vesu Residential Belt',
    lat: 21.142400,
    lon: 72.796200,
    latitude: 21.142400,
    longitude: 72.796200,
    status: 'normal',
    num_lanes: 6,
    has_brts: true,
    is_major: false,
    junction_type: 'residential',
    description: 'Modern 6-lane boulevard intersection catering to residential communities and high-end retail.',
    connecting_roads: ['VIP Road', 'Vesu Canal Road', 'Abhva Link Road'],
    google_maps_url: 'https://www.google.com/maps?q=21.142400,72.796200'
  },
  {
    id: 'J-013',
    name: 'Amroli Cross Road',
    slug: 'amroli-cross-road',
    area: 'Amroli / Katargam Link',
    lat: 21.238100,
    lon: 72.848400,
    latitude: 21.238100,
    longitude: 72.848400,
    status: 'normal',
    num_lanes: 4,
    has_brts: true,
    is_major: false,
    junction_type: 'transit',
    description: 'Northern Tapi river crossing node providing connectivity to Sayan and Bharuch highway links.',
    connecting_roads: ['Amroli Bridge Road', 'Katargam Road', 'Kosamba Highway'],
    google_maps_url: 'https://www.google.com/maps?q=21.238100,72.848400'
  },
  {
    id: 'J-014',
    name: 'Pandesara GIDC Cross',
    slug: 'pandesara-gidc',
    area: 'Pandesara Industrial Zone',
    lat: 21.123400,
    lon: 72.835400,
    latitude: 21.123400,
    longitude: 72.835400,
    status: 'critical',
    num_lanes: 4,
    has_brts: false,
    is_major: true,
    junction_type: 'industrial',
    description: 'Heavy chemical and textile manufacturing GIDC intersection with substantial heavy vehicle and logistics traffic.',
    connecting_roads: ['GIDC Main Road', 'Udhna-Navsari Road', 'Bamroli Road'],
    google_maps_url: 'https://www.google.com/maps?q=21.123400,72.835400'
  },
  {
    id: 'J-015',
    name: 'Sarthana Jakat Naka',
    slug: 'sarthana-jakat-naka',
    area: 'Kamrej Highway Corridor',
    lat: 21.232200,
    lon: 72.891400,
    latitude: 21.232200,
    longitude: 72.891400,
    status: 'moderate',
    num_lanes: 6,
    has_brts: true,
    is_major: true,
    junction_type: 'entry_point',
    description: 'Northeastern entrance corridor to Surat connecting the city to NH-48 and the Ahmedabad-Mumbai expressway.',
    connecting_roads: ['Kamrej Road', 'Varachha Extension', 'Nature Park Road'],
    google_maps_url: 'https://www.google.com/maps?q=21.232200,72.891400'
  },
  {
    id: 'J-016',
    name: 'Pal Rander Road',
    slug: 'pal-rander-road',
    area: 'Pal / West Tapi',
    lat: 21.210200,
    lon: 72.782400,
    latitude: 21.210200,
    longitude: 72.782400,
    status: 'normal',
    num_lanes: 4,
    has_brts: false,
    is_major: false,
    junction_type: 'residential',
    description: 'Connects western sub-cities of Pal and Rander along green residential corridors.',
    connecting_roads: ['Pal Canal Road', 'Rander Road', 'Hazira Link'],
    google_maps_url: 'https://www.google.com/maps?q=21.210200,72.782400'
  },
  {
    id: 'J-017',
    name: 'Ring Road Rustampura',
    slug: 'ring-road-rustampura',
    area: 'Textile Market Belt',
    lat: 21.181400,
    lon: 72.835400,
    latitude: 21.181400,
    longitude: 72.835400,
    status: 'critical',
    num_lanes: 6,
    has_brts: true,
    is_major: true,
    junction_type: 'commercial',
    description: 'Core junction of the Surat textile market district with high loading/unloading logistics activity and BRTS lane flow.',
    connecting_roads: ['Ring Road', 'Salabatpura Main Road', 'Millennium Market Road'],
    google_maps_url: 'https://www.google.com/maps?q=21.181400,72.835400'
  },
  {
    id: 'J-018',
    name: 'City Light Junction',
    slug: 'city-light',
    area: 'Citylight Commercial',
    lat: 21.162400,
    lon: 72.802400,
    latitude: 21.162400,
    longitude: 72.802400,
    status: 'normal',
    num_lanes: 4,
    has_brts: false,
    is_major: false,
    junction_type: 'commercial',
    description: 'Intersecting City Light main road and Science Centre bypass, surrounded by shopping complexes.',
    connecting_roads: ['City Light Main Road', 'Anuvrat Dwar Marg', 'Science Centre Road'],
    google_maps_url: 'https://www.google.com/maps?q=21.162400,72.802400'
  },
  {
    id: 'J-019',
    name: 'Kadodara Highway Cross',
    slug: 'kadodara-highway',
    area: 'Eastern National Highway Hub',
    lat: 21.171400,
    lon: 72.910400,
    latitude: 21.171400,
    longitude: 72.910400,
    status: 'moderate',
    num_lanes: 6,
    has_brts: false,
    is_major: true,
    junction_type: 'entry_point',
    description: 'Key junction linking NH-53 / NH-48 freight logistics into the eastern industrial periphery of Surat.',
    connecting_roads: ['Kadodara Highway', 'Bardoli Road', 'Surat East Bypass'],
    google_maps_url: 'https://www.google.com/maps?q=21.171400,72.910400'
  },
  {
    id: 'J-020',
    name: 'Dumas Beach Cross Road',
    slug: 'dumas-beach-cross',
    area: 'Airport / Coastal Strip',
    lat: 21.095400,
    lon: 72.725400,
    latitude: 21.095400,
    longitude: 72.725400,
    status: 'normal',
    num_lanes: 4,
    has_brts: false,
    is_major: false,
    junction_type: 'entry_point',
    description: 'Southwestern gateway connecting Surat International Airport corridor to the coastal Dumas tourism area.',
    connecting_roads: ['Dumas Main Road', 'Airport Bypass', 'Sultanabad Road'],
    google_maps_url: 'https://www.google.com/maps?q=21.095400,72.725400'
  }
];



